/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface VaultHubPermissionInterface extends utils.Interface {
  functions: {
    "getLabelExistPermit(address,address,uint256,uint8,bytes32,bytes32,bytes32)": FunctionFragment;
    "getLabelNamePermit(address,uint256,uint64,uint8,bytes32,bytes32,bytes32)": FunctionFragment;
    "hasMintedPermit(address,uint256,uint8,bytes32,bytes32,bytes32)": FunctionFragment;
    "hasRegisterPermit(address,uint256,uint8,bytes32,bytes32,bytes32)": FunctionFragment;
    "initPermit(address,uint256,uint8,bytes32,bytes32,bytes32)": FunctionFragment;
    "mintSavePermit(address,string,string,address,address,uint256,uint8,bytes32,bytes32,bytes32)": FunctionFragment;
    "queryByIndexPermit(address,uint64,uint256,uint8,bytes32,bytes32,bytes32)": FunctionFragment;
    "queryByNamePermit(address,address,uint256,uint8,bytes32,bytes32,bytes32)": FunctionFragment;
    "queryPrivateVaultAddressPermit(address,uint256,uint8,bytes32,bytes32,bytes32)": FunctionFragment;
    "saveWithoutMintPermit(address,string,string,address,uint256,uint8,bytes32,bytes32,bytes32)": FunctionFragment;
    "totalSavedItemsPermit(address,uint256,uint8,bytes32,bytes32,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getLabelExistPermit"
      | "getLabelNamePermit"
      | "hasMintedPermit"
      | "hasRegisterPermit"
      | "initPermit"
      | "mintSavePermit"
      | "queryByIndexPermit"
      | "queryByNamePermit"
      | "queryPrivateVaultAddressPermit"
      | "saveWithoutMintPermit"
      | "totalSavedItemsPermit"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getLabelExistPermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getLabelNamePermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hasMintedPermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRegisterPermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initPermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mintSavePermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "queryByIndexPermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "queryByNamePermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "queryPrivateVaultAddressPermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "saveWithoutMintPermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSavedItemsPermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLabelExistPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLabelNamePermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasMintedPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRegisterPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initPermit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintSavePermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryByIndexPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryByNamePermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryPrivateVaultAddressPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "saveWithoutMintPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSavedItemsPermit",
    data: BytesLike
  ): Result;

  events: {};
}

export interface VaultHubPermission extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VaultHubPermissionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getLabelExistPermit(
      addr: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    getLabelNamePermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    hasMintedPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    hasRegisterPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    initPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    mintSavePermit(
      addr: PromiseOrValue<string>,
      data: PromiseOrValue<string>,
      cryptoLabel: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    queryByIndexPermit(
      addr: PromiseOrValue<string>,
      index: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    queryByNamePermit(
      addr: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    queryPrivateVaultAddressPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    saveWithoutMintPermit(
      addr: PromiseOrValue<string>,
      data: PromiseOrValue<string>,
      cryptoLabel: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    totalSavedItemsPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  getLabelExistPermit(
    addr: PromiseOrValue<string>,
    labelHash: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  getLabelNamePermit(
    addr: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    index: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  hasMintedPermit(
    addr: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  hasRegisterPermit(
    addr: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  initPermit(
    addr: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  mintSavePermit(
    addr: PromiseOrValue<string>,
    data: PromiseOrValue<string>,
    cryptoLabel: PromiseOrValue<string>,
    labelHash: PromiseOrValue<string>,
    receiver: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  queryByIndexPermit(
    addr: PromiseOrValue<string>,
    index: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  queryByNamePermit(
    addr: PromiseOrValue<string>,
    labelHash: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  queryPrivateVaultAddressPermit(
    addr: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  saveWithoutMintPermit(
    addr: PromiseOrValue<string>,
    data: PromiseOrValue<string>,
    cryptoLabel: PromiseOrValue<string>,
    labelHash: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  totalSavedItemsPermit(
    addr: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    getLabelExistPermit(
      addr: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    getLabelNamePermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasMintedPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRegisterPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    initPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    mintSavePermit(
      addr: PromiseOrValue<string>,
      data: PromiseOrValue<string>,
      cryptoLabel: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    queryByIndexPermit(
      addr: PromiseOrValue<string>,
      index: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    queryByNamePermit(
      addr: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    queryPrivateVaultAddressPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    saveWithoutMintPermit(
      addr: PromiseOrValue<string>,
      data: PromiseOrValue<string>,
      cryptoLabel: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    totalSavedItemsPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getLabelExistPermit(
      addr: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLabelNamePermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasMintedPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasRegisterPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintSavePermit(
      addr: PromiseOrValue<string>,
      data: PromiseOrValue<string>,
      cryptoLabel: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queryByIndexPermit(
      addr: PromiseOrValue<string>,
      index: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queryByNamePermit(
      addr: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queryPrivateVaultAddressPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    saveWithoutMintPermit(
      addr: PromiseOrValue<string>,
      data: PromiseOrValue<string>,
      cryptoLabel: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalSavedItemsPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getLabelExistPermit(
      addr: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLabelNamePermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasMintedPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasRegisterPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mintSavePermit(
      addr: PromiseOrValue<string>,
      data: PromiseOrValue<string>,
      cryptoLabel: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queryByIndexPermit(
      addr: PromiseOrValue<string>,
      index: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queryByNamePermit(
      addr: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queryPrivateVaultAddressPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    saveWithoutMintPermit(
      addr: PromiseOrValue<string>,
      data: PromiseOrValue<string>,
      cryptoLabel: PromiseOrValue<string>,
      labelHash: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSavedItemsPermit(
      addr: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      DOMAIN_SEPARATOR: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
