/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as multiSignWalletSol from "./MultiSignWallet.sol";
import type * as seedSol from "./Seed.sol";

export type { multiSignWalletSol };

export type { seedSol };
export type { Treasury } from "./Treasury";
