/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as orderBookSol from "./OrderBook.sol";

export type { orderBookSol };
export type { ERC20Mock } from "./ERC20Mock";
