/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as constantsSol from "./Constants.sol";
import type * as permissionSol from "./Permission.sol";

export type { constantsSol };

export type { permissionSol };
